import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        {/* sidebar navigation */}
        <nav style={{ width: 200, background: '#0b1220', color: '#e5e7eb', minHeight: '100vh', padding: '20px 10px' }}>
          <h2 style={{ fontSize: 18, marginBottom: 20 }}>AML System</h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, lineHeight: 2 }}>
            <li><a href="/" style={{ color: 'inherit', textDecoration: 'none' }}>Dashboard</a></li>
            <li><a href="/alert_management" style={{ color: 'inherit', textDecoration: 'none' }}>Alert Management</a></li>
            <li><a href="/case_management" style={{ color: 'inherit', textDecoration: 'none' }}>Case Management</a></li>
            <li><a href="/str" style={{ color: 'inherit', textDecoration: 'none' }}>STR Module</a></li>
            <li><a href="/regulator" style={{ color: 'inherit', textDecoration: 'none' }}>Regulator</a></li>
            <li><a href="/admin" style={{ color: 'inherit', textDecoration: 'none' }}>Admin Management</a></li>
          </ul>
        </nav>
        <main style={{ flex: 1 }}>
          {children}
        </main>
      </body>
    </html>
  );
}
